// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import CollapsibleController from "./collapsible_controller"
import NewLocationController from "./new_location_controller"

application.register("collapsible", CollapsibleController)
application.register("new-location", NewLocationController)
